packages:
  - "packages/*"
  - "docs/"

allowBuilds:
  sharp: true
  esbuild: true
  playwright: true

fetchTimeout: 300000
fetchRetries: 10

supportedArchitectures:
  os:
    - current
    - win32
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl