packages:
  - "packages/*"
  - "docs/"

allowBuilds:
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - playwright

supportedArchitectures:
  os: [current, linux]
  cpu: [current, x64]
  libc: [current, glibc]

