packages:
  - "packages/*"
  - "docs/"

allowBuilds:
  sharp: true
  esbuild: true
  playwright: true

fetchTimeout: 300000
fetchRetries: 10

supportedArchitectures:
  os:
    - current
  cpu:
    - current
  libc:
    - current

minimumReleaseAgeExclude:
  - astro@7.2.9
