/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BarChart {
        /**
          * @default "Hello World"
         */
        "title": string;
    }
}
declare global {
    interface HTMLBarChartElement extends Components.BarChart, HTMLStencilElement {
    }
    var HTMLBarChartElement: {
        prototype: HTMLBarChartElement;
        new (): HTMLBarChartElement;
    };
    interface HTMLElementTagNameMap {
        "bar-chart": HTMLBarChartElement;
    }
}
declare namespace LocalJSX {
    interface BarChart {
        /**
          * @default "Hello World"
         */
        "title"?: string;
    }

    interface BarChartAttributes {
        "title": string;
    }

    interface IntrinsicElements {
        "bar-chart": Omit<BarChart, keyof BarChartAttributes> & { [K in keyof BarChart & keyof BarChartAttributes]?: BarChart[K] } & { [K in keyof BarChart & keyof BarChartAttributes as `attr:${K}`]?: BarChartAttributes[K] } & { [K in keyof BarChart & keyof BarChartAttributes as `prop:${K}`]?: BarChart[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bar-chart": LocalJSX.IntrinsicElements["bar-chart"] & JSXBase.HTMLAttributes<HTMLBarChartElement>;
        }
    }
}
